<a href="https://colab.research.google.com/github/thebabycode/Neural-Networks-and-Deep-Learning/blob/main/NNDL_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Explore MLP

Multi-layer Perceptron (MLP) is a supervised learning algorithm that learns a function  by training on a dataset, where  is the number of dimensions for input and  is the number of dimensions for output. Given a set of features  and a target , it can learn a non-linear function approximator for either classification or regression.

hidden_layer_sizes : This parameter allows us to set the number of layers and the number of nodes we wish to have in the Neural Network Classifier. Each element in the tuple represents the number of nodes at the ith position where i is the index of the tuple. Thus the length of tuple denotes the total number of hidden layers in the network.

max_iter: It denotes the number of epochs.

activation: The activation function for the hidden layers.

solver: This parameter specifies the algorithm for weight optimization across the nodes.

random_state: The parameter allows to set a seed for reproducing the same results

#Summary of Parameters

hidden_layer_sizestuple, length = n_layers - 2, default=(100,)
The ith element represents the number of neurons in the ith hidden layer.

activation{‘identity’, ‘logistic’, ‘tanh’, ‘relu’}, default=’relu’
Activation function for the hidden layer.

‘identity’, no-op activation, useful to implement linear bottleneck, returns f(x) = x

‘logistic’, the logistic sigmoid function, returns f(x) = 1 / (1 + exp(-x)).

‘tanh’, the hyperbolic tan function, returns f(x) = tanh(x).

‘relu’, the rectified linear unit function, returns f(x) = max(0, x)



solver{‘lbfgs’, ‘sgd’, ‘adam’}, default=’adam’
The solver for weight optimization.

‘lbfgs’ is an optimizer in the family of quasi-Newton methods.

‘sgd’ refers to stochastic gradient descent.

‘adam’ refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy Ba

Note: The default solver ‘adam’ works pretty well on relatively large datasets (with thousands of training samples or more) in terms of both training time and validation score.

For small datasets, however, ‘lbfgs’ can converge faster and perform better.

In [ ]:
import numpy as np
import sklearn
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier

#XOR

In [ ]:
input = np.array([
    0, 0,
    0, 1,
    1, 0,
    1, 1
]).reshape(4, 2)
print(" input values X  and Y :\n",input)

actual_output = np.array([0, 1, 1, 0]).reshape(4,)
print(" the expected output is \n",actual_output)

 input values X  and Y :
 [[0 0]
 [0 1]
 [1 0]
 [1 1]]
 the expected output is 
 [0 1 1 0]


In [ ]:
model = sklearn.neural_network.MLPClassifier(
    activation='relu',solver='sgd', max_iter=10000, hidden_layer_sizes=(4,2))
model.fit(input, actual_output)

print('model score:', model.score(input, actual_output)) 
print('predicted output:', model.predict(input)) 
print('expected output:', np.array([0, 1, 1, 0]))
print(model.coefs_)


model score: 1.0
predicted output: [0 1 1 0]
expected output: [0 1 1 0]
[array([[ 1.16660146, -0.10559167, -0.91010311, -0.99688677],
       [ 1.16696446, -0.04886255,  1.37166369,  0.03374334]]), array([[-1.54728126,  1.49084288],
       [-0.3687397 , -0.79798713],
       [ 1.25603498, -0.70502781],
       [-1.3535689 ,  0.39860443]]), array([[ 2.61475938],
       [-1.66831793]])]


In [ ]:
model = sklearn.neural_network.MLPClassifier(
    activation='relu',solver='adam', max_iter=10000, hidden_layer_sizes=(4,2))
model.fit(input, actual_output)

print('model score:', model.score(input, actual_output)) 
print('predicted output:', model.predict(input)) 
print('expected output:', np.array([0, 1, 1, 0]))
print(model.coefs_)


model score: 1.0
predicted output: [0 1 1 0]
expected output: [0 1 1 0]
[array([[-7.99231477e-01, -1.09053981e+00, -5.00156375e-21,
        -8.25375797e-01],
       [-7.99363151e-01, -1.09083988e+00,  1.61216229e-06,
        -8.25911332e-01]]), array([[ 1.87002987e+00, -1.37903314e+00],
       [-1.63640155e+00,  1.93553610e+00],
       [ 2.44209825e-03, -3.03693228e-36],
       [-8.16467150e-01,  2.33576531e+00]]), array([[ 2.34867633],
       [-1.84369638]])]


In [ ]:
model = sklearn.neural_network.MLPClassifier(
    activation='tanh',solver='lbfgs', max_iter=10000, hidden_layer_sizes=(4,2))
model.fit(input, actual_output)

print('model score:', model.score(input, actual_output)) 
print('predicted output:', model.predict(input)) 
print('expected output:', np.array([0, 1, 1, 0]))
print(model.coefs_)


model score: 1.0
predicted output: [0 1 1 0]
expected output: [0 1 1 0]
[array([[ 0.7590344 ,  1.5367596 , -0.32331984, -1.80644109],
       [-0.35119925, -1.84410419, -0.29724773,  2.3232241 ]]), array([[-0.36928357, -0.41570933],
       [ 0.89301852,  2.87650058],
       [-0.03176853,  0.91972259],
       [ 0.39115829,  3.03530492]]), array([[-0.46661804],
       [-8.82565836]])]


In [ ]:
# lbfgs’, ‘sgd’, ‘adam’
model = sklearn.neural_network.MLPClassifier(
    activation='logistic',solver='lbfgs', max_iter=10000, hidden_layer_sizes=(4,2))
model.fit(input, actual_output)
print(model.coefs_[1])
print('model score:', model.score(input, actual_output)) 
print('predicted output:', model.predict(input)) 
print('expected output:', np.array([0, 1, 1, 0]))
print(model.coefs_)


[[ 3.76994212 -6.62133386]
 [-0.2753963   0.80230956]
 [-1.82159125  2.60732572]
 [-2.79035065  5.00786113]]
model score: 1.0
predicted output: [0 1 1 0]
expected output: [0 1 1 0]
[array([[4.60298389, 0.31257021, 2.44906389, 3.92082107],
       [4.72851497, 0.40838812, 2.99598954, 3.64772646]]), array([[ 3.76994212, -6.62133386],
       [-0.2753963 ,  0.80230956],
       [-1.82159125,  2.60732572],
       [-2.79035065,  5.00786113]]), array([[  5.46548763],
       [-13.48872725]])]


In [ ]:
model = sklearn.neural_network.MLPClassifier(
    activation='identity',solver='sgd',  max_iter=10000, hidden_layer_sizes=(4,3))
model.fit(input, actual_output)

print('model score:', model.score(input, actual_output)) 
print('predicted output:', model.predict(input)) 
print('expected output:', np.array([0, 1, 1, 0]))


model score: 0.75
predicted output: [0 1 1 1]
expected output: [0 1 1 0]


In [ ]:
model = sklearn.neural_network.MLPClassifier(
    activation='identity',solver='lbfgs',  max_iter=10000, hidden_layer_sizes=(4,3))
model.fit(input, actual_output)

print('model score:', model.score(input, actual_output)) 
print('predicted output:', model.predict(input)) 
print('expected output:', np.array([0, 1, 1, 0]))


model score: 0.25
predicted output: [1 1 0 1]
expected output: [0 1 1 0]


In [ ]:
model = sklearn.neural_network.MLPClassifier(
    activation='identity',solver='adam',  max_iter=10000, hidden_layer_sizes=(4,3))
model.fit(input, actual_output)

print('model score:', model.score(input, actual_output)) 
print('predicted output:', model.predict(input)) 
print('expected output:', np.array([0, 1, 1, 0]))
print(model.coefs_)


model score: 0.5
predicted output: [1 1 0 0]
expected output: [0 1 1 0]
[array([[ 0.08111146,  0.09309657,  0.75117389,  0.44926889],
       [ 0.27371772, -0.52647821,  0.25183616,  0.1371285 ]]), array([[-4.30431447e-01,  9.16631302e-01,  2.14498372e-04],
       [-8.63046022e-01, -3.12617333e-01,  1.46074174e-01],
       [-1.51632867e-01,  6.45416566e-01, -3.84743179e-01],
       [ 4.38066139e-01, -5.65595842e-01,  7.36755258e-01]]), array([[ 1.04599174],
       [-1.0398871 ],
       [-0.40530059]])]


From comparing the predicted and expected ouput with all other activation functions we observe that "identity activation" with solver "lbfgs" doesnt give expected output with its predcited output